<?php

namespace catcoderphp\usermonitor;


use yii\base\Application;
use yii\base\Module;
use Yii;

class UserMonitor extends Module {


    public $applicationIdentifier;

    public $userIp;

    public $user;

    /**
     * init event handler of functions
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $app = Yii::$app;

        $app->on(Application::EVENT_BEFORE_ACTION,[
            $this,"onEventBeforeAction"
        ]);

        $app->on(Application::EVENT_AFTER_REQUEST,[
            $this, "onEventAfterRequest"
        ]);
    }

    /**
     * even trigger from init
     */
    public function onEventBeforeAction() {
        echo "hola mundo antes de la accion";
    }

    public function onEventAfterRequest() {
        echo "hola mundo despues de la request";
    }

    /**
     * @return int|null|string
     */
    public static function findModuleIdentifier()
    {
        foreach (Yii::$app->modules as $name => $module) {
            $class = null;
            if (is_string($module))
                $class = $module;
            elseif (is_array($module)) {
                if (isset($module['class']))
                    $class = $module['class'];
            } else
                $class = $module::className();
            $parts = explode('\\', $class);
            if ($class && strtolower(end($parts)) == 'usermonitor')
                return $name;
        }
        return null;
    }

}