<?php

namespace catcoderphp\usermonitor;


use catcoderphp\usermonitor\components\SpecialCase;
use yii\base\Application;
use yii\base\Event;
use yii\base\Module;
use Yii;

class UserMonitor extends Module {

    public $applicationIdentifier;
    public $userIp;
    public $user;
    public $currentURI;
    /**
     * init event handler of functions
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $app = Yii::$app;

        $app->on(Application::EVENT_BEFORE_ACTION,[
            $this,"onEventBeforeAction"
        ]);

        $app->on(Application::EVENT_AFTER_REQUEST,[
            $this, "onEventAfterRequest"
        ]);
        $this->on(SpecialCase::SPECIAL_CASE,[
            $this,"onSpecialCase"
        ]);

    }

    /**
     * even trigger from init
     */
    public function onEventBeforeAction() {
        //print_r($this->currentURI);
        //echo Yii::$app->request->queryString;
    }

    public function onEventAfterRequest($event) {
        print_r($event);die;
        echo $this->currentURI;

        //echo "hola mundo despues de la request";
    }

    public function save($params) {
        print_r($params);die;
    }

    public function onSpecialCase() {
        echo "hola";die;
    }


}